<?php

/**
 * @file
 * Contains ckeditor_entity_link.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function ckeditor_entity_link_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the ckeditor_entity_link module.
    case 'help.page.ckeditor_entity_link':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Allows to insert entity links in CKEditor.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_page_attachments
 * Attach ckeditor entity links configuration to drupalsettings
 */
function ckeditor_entity_link_page_attachments(array &$attachments) {
  $config = \Drupal::config('ckeditor_entity_link.settings');
  $entityTypes = $config->get('entity_types');
  $enabledEntity = [];
  if (is_array($entityTypes)) {
    foreach ($entityTypes as $entity) {
      if ($entity != 0) {
        $enabledEntity[$entity] = $entity;
      }
    }
  }
  $attachments['#attached']['drupalSettings']['ckeditor_entity_link'] = $enabledEntity;
}
